//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryCreator.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceList
    {
        public int id { get; set; }
        public string region_name { get; set; }
        public decimal price_before_10_kg { get; set; }
        public decimal price_after_10_kg { get; set; }
    }
}
